dist: xenial
language: python
python: 3.6
install: "pip install tox"
script: "tox -e $TRAVIS_BUILD"

matrix:
  include:
    - env: TRAVIS_BUILD=coverage
      before_install: "pip install codecov"
      after_success: "codecov"
    - env: TRAVIS_BUILD=py36-dev
    - env: TRAVIS_BUILD=lint
      before_install: "nvm use stable"
      script: "make && make lint"

cache:
  directories:
    - $HOME/.cache
